version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment: 
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPASSWORD=password
      - PGDATABASE=postgres
      - PGPORT=5432

  postgres:
    build: ./postgresDocker
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"