version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment: 
      - POSTGRES_URL=postgres://postgres:password@localhost:5432/postgres
      - PGUSER=postgres
      - PGHOST=localhost
      - PGPASSWORD=password
      - PGDATABASE=postgres
      - PGPORT=5432

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"